name: gravipy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - harmonica
  - xarray
  - rioxarray
  - verde
  - pyproj
  - scikit-learn
  - python=3.11
  - pandas
  - matplotlib
  - jupyter
  - geopandas
  - pip
    - tidegravity
